[package]
name = "some"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib","cdylib"]

[dependencies]
cairo-lang-macro = { path = "../../scarb/plugins/cairo-lang-macro"}
indoc = "*"
