name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:


jobs:
  unfixed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change lock file
        run: echo "# unfixed" >> lockfile
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.8.2"
      - name: Test
        run: scarb build

  fixed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change lock file
        run: echo "# fixed" >> lockfile      
      - uses: software-mansion/setup-scarb@maciektr/cache-save-dangling
        with:
          scarb-version: "2.8.2"
      - name: Test
        run: scarb build
