name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:


jobs:
  current_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Build Cairo
        run: |
            git clone https://github.com/starkware-libs/cairo.git
            cd cairo
            git checkout v2.7.1
            cargo build --release
            echo "$GITHUB_WORKSPACE/cairo/target/release" >> $GITHUB_PATH

      - name: Test
        run: cairo-test .

  current_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Build Cairo
        run: |
            git clone https://github.com/starkware-libs/cairo.git
            cd cairo
            cargo build --release
            echo "$GITHUB_WORKSPACE/cairo/target/release" >> $GITHUB_PATH

      - name: Test
        run: cairo-test .      