name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Clone Scarb
        run: git clone https://github.com/software-mansion/scarb.git
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "scarb -> target"
      - name: Build Scarb
        run: |
          cd scarb 
          git checkout maciektr/proc-macro-enable-v1-tests
          cargo build -p scarb --profile=ci
          cd ..
      - run: |
          ./scarb/target/ci/scarb build --test
