name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:


jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      # - name: Install Scarb
      #   run: |
      #       git clone https://github.com/software-mansion/scarb.git
      #       cd scarb
      #       git checkout 055a9854905ddc0882fe22a67fe04a9702084601
      #       cargo build --release
      #       echo "$GITHUB_WORKSPACE/scarb/target/release" >> $GITHUB_PATH

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.6.4"


      - name: Test
        run: |
          ls .
          cd foo && scarb update
          ls ../
