name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:


jobs:
  current_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.7.1"

      - name: Test
        run: scarb build -p contracts

  current_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Clone Scarb
        run: git clone https://github.com/software-mansion/scarb.git

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "scarb"

      - name: Install Scarb
        run: |
            cd scarb
            cargo build --release
            echo "$GITHUB_WORKSPACE/scarb/target/release" >> $GITHUB_PATH

      - name: Test
        run: scarb build -p contracts