name: CI

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:


jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Change lock file
        run: echo "# unfixed" >> lockfile
      - uses: software-mansion/setup-scarb@main
        with:
          scarb-version: "2.8.4"
          scarb-lock: "./some/sub/dir/Scarb.lock"
      - name: Test
        run: scarb build
